openapi: 3.0.1
info:
  contact:
    email: lampralexandros@gmail.com
  description: This is a sample openApi document
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://wabli.netlify.app/
  title: TempApi
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- description: local-host
  url: http://localhost:8090/v1
security:
- {}
tags:
- description: not yet ready
  name: product
paths:
  /product:
    post:
      operationId: createproduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/product'
        description: data to be created
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product'
          description: successful operation
      summary: Creates the data
      tags:
      - product
      x-eov-operation-handler: controllers/ProductController
  /product/{productId}:
    delete:
      operationId: deleteproduct
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: productId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: successful operation
      summary: Delete the element
      tags:
      - product
      x-eov-operation-handler: controllers/ProductController
    get:
      operationId: getproduct
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: productId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product'
          description: successful operation
      summary: Get the element
      tags:
      - product
      x-eov-operation-handler: controllers/ProductController
    put:
      operationId: updateproduct
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: productId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/product'
        description: data to be updated
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product'
          description: successful operation
      summary: Updates the element
      tags:
      - product
      x-eov-operation-handler: controllers/ProductController
  /product/getAll:
    get:
      operationId: getAllproduct
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/product'
                type: array
          description: successful operation
      summary: Get all the data
      tags:
      - product
      x-method-getAll: "true"
      x-eov-operation-handler: controllers/ProductController
components:
  schemas:
    product:
      example:
        pTitle: pTitle
        _id: _id
        pCount: 0.8008281904610115
        pImage:
          data: data
          name: name
      properties:
        _id:
          type: string
        pTitle:
          type: string
        pCount:
          format: double
          type: number
        pImage:
          $ref: '#/components/schemas/product_pImage'
      required:
      - pCount
      - pImage
      - pTitle
      type: object
    product_pImage:
      example:
        data: data
        name: name
      properties:
        data:
          type: string
        name:
          type: string
      type: object
      x-isSchemaOnly: "true"
